<?php

########################################################################
# Extension Manager/Repository config file for ext: "leonex_symfony_serializer"
#
# Auto generated by Extension Builder 2011-09-12
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Serializer',
	'description' => 'This extension utilizes the Symfony serializer library to provide a good serializer.',
	'category' => 'services',
	'author' => 'Elmar Athmer',
	'author_email' => 'athmer@leonex.de',
	'author_company' => 'Leonex',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>